### ISSUE TITLE
Vue 인스턴스에서 Payload는 못넘기나요??

### ISSUE THREAD

**Issue by freevue** [AhaOfficial/vue-state-store#1]
`Store`의 `Action`이 일어나는 곳인 `update`부분으로 알고 있습니다. 그리고 `calback`부분에 `state`만 들어가고 있습니다.

```typescript
async update(callback: Interface.Updater<T> | Interface.AsyncUpdater<T>) {
    await this.set(await callback(this.value))
}
```

인스턴스 단에서 Payload를 넘겨주는 방법은 권장하지 않는 건가요??

**Comment by hm-lee** [comment]
@freevuehub 
인스턴스 단에서 payload 를 넘긴다면
예를 들면 어떤 형식이 될 수 있을까요?

**Comment by freevuehub** [comment]
다시 보니 제가 잘못이해하고 있었습니다.

```typescript
// ...
upVote() {
    this.update((data) => {
        data.upVoteCount += 1
        return data
    })
}
// ...
```

이렇게 선언을 하고,

```javascript
// ...
setup() {
    setInterval(() => vote.upVote(), 1000)

    return {
        $vote: vote.bind()
    }
}
// ...
```

이렇게 사용하고 있어서, 만약 `vote.upVote()`이 부분을 `vote.upVote(10)`이렇게 넘기면 `10`을 받을 수 없는 줄 알았는데 `update`가 `upVote`에서 받으면 사용할 수 있네요.

**Comment by hm-lee** [comment]
@freevuehub 
아하, 네네 그러한 내장된 액션에 필요한 payload 는
Pure-Typescript 틱하게 내장함수 인자로 구성해주시면 됩니다 😊
