### ISSUE TITLE
The Polish README is missing

### ISSUE THREAD

**Issue by Milesq** [AhaOfficial/vue-state-store#4]
I can take care about this

**Comment by hm-lee** [comment]
OK i'll provide you basic template for the writing. 😊

**Comment by hm-lee** [comment]
i added temporary README.PL.md https://github.com/AhaOfficial/vue-state-store/commit/11a0847cdac297b7ef9fd2c1907bd6bb606aa589
I sent you an e-mail with the permission to write the project, so please check it. 😊

**Comment by Milesq** [comment]
I haven't translated for the last time, I have one paragraph left, I'll add a file soon

**Comment by hm-lee** [comment]
@Milesq so much thanks 😊 
i'll going to post an ad for this module soon
(perhaps twitter or madewithvue?)
Thank you for working on it 😊😊😊
